apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odoo-main
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/kacpi52/odoo-gitops'
    path: base
    targetRevision: main #match with your branch name 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: odoo  #match with your k8s manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true